Fitur Edit Transaksi dari Daftar
dewzzjr/angkutgan pull request #5
Opened 2021-02-22 12:35 UTC by bdulkim

2021-02-28 01:12 UTC, dewzzjr requested changes

2021-02-28 01:12 UTC, dewzzjr commented on frontend/assets/js/admin.js
> +    username: '',
validate usernamenya belum ada nih

2021-02-28 01:12 UTC, dewzzjr commented on frontend/penjualan/daftar.html
>              </tr>
daftar uda ada endpointnya di commit paling akhir dicoba dulu

2021-02-28 01:14 UTC, dewzzjr commented on frontend/admin/tambah.html
> +			<input name="code" required type="text" class="form-control" id="codeAdd" style="text-transform:uppercase" />
ini dibikin lowercase, nanti pas kirim datanya di sanitize biar ga ada space besar kecil, username yang boleh cuma huruf kecil sama angka aja

2021-02-28 11:27 UTC, bdulkim commented on frontend/assets/js/admin.js
> +    username: '',
validate seperti apa dew?

awal e pengen cek apakah username udah ada di database apa belum dengan memanfaatkan get users tapi kayane belum ada, sementara diatasi ning handler nek gagal submit artine username udah ada di database

terus secara default iki di bagian username udah ga bisa ngetik spasi, cuma bisa alfanumerik

2021-02-28 11:28 UTC, bdulkim commented on frontend/penjualan/daftar.html
>              </tr>
oiya wes dicoba sebetul e, cuma lali nek sempet hardcode bagian iki

2021-02-28 11:32 UTC, bdulkim commented on frontend/admin/tambah.html
> +			<input name="code" required type="text" class="form-control" id="codeAdd" style="text-transform:uppercase" />
default ga bisa input space di form nya

2021-03-02 11:49 UTC, dewzzjr commented on frontend/assets/js/admin.js
> +    username: '',
kemaren kan tak kasi contoh ini

```
curl --location --request GET 'http://localhost:8000/ajax?action=username&new=test&old=test'
```

2021-03-07 02:12 UTC, bdulkim commented on frontend/assets/js/admin.js
> +    username: '',
coba cek latest push dew

2021-03-14 03:05 UTC, dewzzjr approved these changes
sementara ku deploy tapi nanti revisi yo

2021-03-14 03:05 UTC, dewzzjr commented on frontend/penjualan/daftar.html
> +    </div>
biasakan pake resource yang disediakan, untuk loader uda ada contoh di bootstrap diikutin aja caranya
https://getbootstrap.com/docs/4.4/components/spinners/

2021-03-14 03:05 UTC, merged